---
modules:
  - path: modules/zmk-nice-oled
  
include:
  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_epaper

  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_view_custom

  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left